name: "Deploy a branch version of the website"

on:
  pull_request:

env:
  HUGO_VERSION: 0.123.4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ github.head_ref }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Debug print branch name
        shell: bash
        run: echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Download hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -zxvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo

      - name: Build the website
        run: ./hugo -b https://webtest.ivoa.info/v/${{ env.BRANCH_NAME }}

      - name: Upload the branch version of the website
        uses: Dylan700/sftp-upload-action@latest
        with:
          username: webstage
          server: web.ivoa.net
          key: ${{ secrets.STAGE_ID }}
          uploads: |
            ./public/ => ./ivoa-web-stage/v/${{ env.BRANCH_NAME }}
